import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import Toast from "@/components/ui/Toast";
import Footer from "@/components/layout/Footer";
import { ShopProvider } from "@/context/ShopContext";
import Providers from "@/providers/ClerkProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={inter.variable}
    >
      
      <body className="min-h-full flex flex-col">
          <Providers>
          <ShopProvider>
           <Navbar />
        {children}
         <Toast />     
         </ShopProvider>
         </Providers>
        <Footer />
        </body>
       
    </html>
  );
}
